name: huffman
description: A dart library for huffman coding
version: 1.0.0
repository: https://github.com/aadarshadhakalg/huffman-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
